site_name: PyTest Cookbook
site_description: "PyTest Cookbook"

repo_url: https://github.com/Python-Test-Engineer/PYTHON-TEST-FRAMEWORK
repo_name: Python-Test-Engineer/PYTHON-TEST-FRAMEWORK

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material" # readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings
  - blog:
      blog_dir: blog
      blog_toc: true
      archive: true
      archive_name: All Articles
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Page tree
nav:
  - "Home": "index.md"

  - "PyTest Full Stack":
      - "About": "pytest/index.md"
      # - "PyTest Core": "pytest/pytest_core.md"
      # - "Minimal": "pytest/pytest_basic.md"
      # - "Main Suite": "pytest/pytest.md"
      # - "API Testing": "playwright_api/api.md"
      # - "e2e Testing": "playwright_api/playwright.md"
      # - "Testing Playgrounds": "playwright_api/testing_playgrounds.md"
  # - "PyTest Extended":
  #     - "About": "pytest/pytest_extended.md"
  #     - "DB Testing": "db_testing/testing.md"
  #     - "Hooks": "pytest/pytest_hooks.md"
  #     - "Hooks Ordering": "pytest/pytest_hooks_order.md"
  #     - "Plugins": "pytest/pytest_plugins.md"
  # - "CLI Apps": "pytest/cli.md"
  # - "CI Integration": "ci_integration/ci_github.md"
  # - "Tox": "ci_integration/tox.md"
  # - "Hypothesis": "hypothesis/index.md"
  - "Django Testing":
      # - "About": "django_testing/index.md"
      - "Setup": "django_testing/setup.md"
      - "Apps": "django_testing/apps.md"
      - "Tests": "django_testing/tests.md"
  # - "How do I...?":
  #     - "About": "how_do_i/index.md"
  #     - "Topic01": "how_do_i/topic01.md"
  #     - "Topic02": "how_do_i/topic02.md"
  - "About Craig":
      - "Services": "craig/services.md"
      - "CV": "craig/cv.md"
      - "Contact": "craig/contact.md"

copyright: |
  &copy; 2024 <a href="https://github.com/Python-Test-Engineer"  target="_blank" rel="noopener">Craig West - PythonTestEngineer.co.uk</a>
