site_name: PyTest Cookbook
site_description: "PyTest Cookbook"

repo_url: https://github.com/Python-Test-Engineer/PYTHON-TEST-FRAMEWORK
repo_name: Python-Test-Engineer/PYTHON-TEST-FRAMEWORK

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material" # readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings
  - blog:
      blog_dir: blog
      blog_toc: true
      archive: true
      archive_name: All Articles
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Page tree
nav:
  - "Home": "index.md"
  - "PyTest Full Stack":
      - "About": "pytest/index.md"
      - "pytest.ini": "pytest/pytest_pytest.ini.md"
      - "Logging": "pytest/pytest_logging.md"
      - "Reading .ini files": "pytest/pytest_ini_files.md"
      - "Custom CSV Output": "pytest/pytest_custom_reports.md"
      - "Custom Console": "pytest/pytest_custom_terminal_reports.md"
  - "Django Testing":
      - "Setup": "django_testing/setup.md"
      - "Apps": "django_testing/apps.md"
      - "Tests": "django_testing/tests.md"
  - "About Craig":
      - "Services": "craig/services.md"
      - "CV": "craig/cv.md"
      - "Courses": "craig/courses.md"
      - "Contact": "craig/contact.md"

copyright: |
  &copy; 2024 <a href="https://github.com/Python-Test-Engineer"  target="_blank" rel="noopener">Craig West - PythonTestEngineer.co.uk</a>
