site_name: PyTest Cookbook
site_description: "PyTest Cookbook"

repo_url: https://github.com/Python-Test-Engineer/PyTest-Full-Stack
repo_name: Python-Test-Engineer/PyTest-Full-Stack

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material" # readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings
  - blog:
      blog_dir: blog
      blog_toc: true
      archive: true
      archive_name: All Articles
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Page tree
nav:
  - "Workshop 2024":
      - "Welcome": "workshop/welcome.md"
      - "Intention": "workshop/intention.md"
      - "Final Project": "workshop/final_project.md"
      - "Build from scratch": "workshop/build_from_scratch.md"
      - "PyTest 101": "workshop/pytest_101.md"
      - "PyTest 102": "workshop/pytest_102.md"
      - "Afterwards": "workshop/afterwards.md"
  - "Motivation": "index.md"
  - "Learn": learn.md
  - "PyTest Full Stack":
      - "Set Up": "pytest/index.md"
      - "Customise": "pytest/pytest_full_stack_customise.md"
      - "Tests": "pytest/pytest_tests.md"
      - "Test Management": "pytest/pytest_test_management.md"
      - "Docker": "pytest/pytest_docker.md"
      - "Allure": "pytest/pytest_allure.md"
      - "Cheat Sheet 1": "pytest/pytest_cheat_sheet.md"
      - "Cheat Sheet 2": "pytest/pytest_cheat2.md"
  - "Asides":
      - "About": "asides/asides.md"
      - "Pluggy": "asides/pluggy.md"
      - "Mocking": "asides/mocking.md"
  - "Toolbox":
      - "About": "toolbox/toolbox_index.md"
      - "Allure Windows ": "toolbox/allure_windows_setup.md"
      - "Pydantic DTS": "toolbox/pydantic_dts.md"
      - "Visual Regression": "toolbox/visual_regression.md"
      - "YoYo PyTest": "toolbox/docker_postgres_yoyo_pytest.md"
      - "Git Essentials": "toolbox/git_essentials.md"
      - "Console prettying": "toolbox/rich_pyboxen.md"
      - "Hatch PyPA": "toolbox/hatch.md"
  - "Docker":
      - "About": "docker/docker_index.md"
      - "Manage Docker with Python": "toolbox/manage_docker_with_python.md"
      - "Docker Postgres": "docker/docker_postgres_setup.md"
      - "PyTest-Docker Plugin": "docker/pytest_docker_plugin.md"
      - "Docker PyTest Image": "docker/docker_flask_pdb.md"
      - "Docker To Go": "docker/docker_to_go.md"
      - "Advanced Docker": "docker/docker_advanced.md"
  - "Django Testing":
      - "Planned": "django_testing/index.md"
  - "About Craig":
      - "Services": "craig/services.md"
      - "CV": "craig/cv.md"
      - "Courses": "craig/courses.md"
      - "Contact": "craig/contact.md"

copyright: |
  &copy; 2024 <a href="https://github.com/Python-Test-Engineer"  target="_blank" rel="noopener">Craig West - pytest-cookbook.com</a>
